name: Deploy GluWise API

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - 'packages/shared/**'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/api/**'
      - 'packages/shared/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci --workspace=packages/shared
        npm ci --workspace=apps/api --no-workspaces
    
    - name: Build shared package
      run: npm run build --workspace=packages/shared
    
    - name: Lint API
      run: npm run lint --workspace=apps/api
    
    - name: Build API
      run: npm run build --workspace=apps/api
    
    - name: Test API
      run: npm run test --workspace=apps/api
      env:
        NODE_ENV: test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Railway
      uses: railwayapp/railway-deploy@v1
      with:
        railway-token: ${{ secrets.RAILWAY_TOKEN }}
        service: gluwise-api
        
    # Alternative: Deploy to Render
    # - name: Deploy to Render
    #   uses: johnbeynon/render-deploy-action@v0.0.8
    #   with:
    #     service-id: ${{ secrets.RENDER_SERVICE_ID }}
    #     api-key: ${{ secrets.RENDER_API_KEY }}
